name = "courses"
type = 'javascript'

account_id = "0668fdd4efcc24407ac6fbcdf14c2d64"
workers_dev = true

main = "src/index.js"
compatibility_date = "2023-01-19"

[vars]
AIRTABLE_BASE_ID = "apps7cHnuhqX5ZYBt"
AIRTABLE_TABLE_NAME = "Courses"
AIRTABLE_URL='https://api.airtable.com/v0'
FORM_URL = "https://course-tracker-bdn.pages.dev/"
